### ISSUE TITLE
Consider tweak to fully visible, fully clipped, and partially visible

### ISSUE THREAD

**Issue by frivoal** [WICG/ScrollAnchoring#1]
The concepts of `fully visible`, `fully clipped`, and `partially visible` are defined in terms of the content area. I believe you should instead use the [optimal viewing region](https://drafts.csswg.org/css-scroll-snap/#optimal-viewing-region).

This allows authors to declare that some portion of the content area isn't actually viewable even when the scroll offset would indicate otherwise, for example because it is obscured by some overlaying element.

**Comment by skobes-chromium** [comment]
Thanks for the suggestion.  I'm not sure if we're ready to introduce a dependency on concepts from the snap points spec.  It looks like Blink hasn't even implemented scroll-padding yet.  But this may make sense in the future.

@ojanvafai @tabatkins FYI

**Comment by tabatkins** [comment]
In the absence of us implementing `scroll-padding` yet, the optimal viewing region is the same as the content area.

I think I agree with Florian; the concept we're trying to capture is indeed the "optimal viewing region" - it helps capture the notion of what you're meant to be looking at.  If something is in the padding region and it changes size, pushing the stuff in the optimal viewing region down, we ideally want to adjust the scroll offset, because that stuff in the padding region might be obscured by floating panels or something.

**Comment by skobes-chromium** [comment]
Ok, I have updated the spec to refer to the optimal viewing region.
